# Generated by Django 4.0.4 on 2022-05-09 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CVE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.URLField()),
                ('verified', models.BooleanField(default=False)),
                ('enumerate', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=32)),
                ('domains', models.ManyToManyField(to='core.domain')),
            ],
        ),
        migrations.CreateModel(
            name='Tech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=50)),
                ('cves', models.ManyToManyField(to='core.cve')),
            ],
        ),
        migrations.CreateModel(
            name='Subdomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('include', models.BooleanField(default=True)),
                ('techs', models.ManyToManyField(to='core.tech')),
            ],
        ),
        migrations.AddField(
            model_name='domain',
            name='subdomains',
            field=models.ManyToManyField(to='core.subdomain'),
        ),
        migrations.AddField(
            model_name='domain',
            name='techs',
            field=models.ManyToManyField(to='core.tech'),
        ),
    ]
