# Generated by Django 4.0.4 on 2022-06-08 05:40

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CVE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('severity', models.CharField(max_length=20)),
                ('score', models.CharField(max_length=5)),
                ('references', models.JSONField(default=core.models.CVE.json_default)),
                ('tech_id', models.CharField(max_length=5)),
                ('cve_id', models.CharField(default='', max_length=50)),
                ('isNew', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('versions', models.JSONField(default=core.models.Tech.json_default)),
                ('color', models.CharField(default='828192', max_length=6)),
                ('cves', models.ManyToManyField(blank=True, related_name='techno', to='core.cve')),
            ],
        ),
        migrations.CreateModel(
            name='Subdomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('include', models.BooleanField(default=True)),
                ('techs_fetched', models.BooleanField(default=False)),
                ('techs', models.ManyToManyField(to='core.tech')),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.URLField(unique=True)),
                ('verified', models.BooleanField(default=False)),
                ('enumerate', models.BooleanField(default=False)),
                ('verify_code', models.PositiveIntegerField()),
                ('photo', models.CharField(blank=True, max_length=550)),
                ('saved_already', models.BooleanField(default=False)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('subdomains', models.ManyToManyField(blank=True, to='core.subdomain')),
                ('techs', models.ManyToManyField(blank=True, to='core.tech')),
            ],
        ),
    ]
