# Generated by Django 4.0.4 on 2022-05-09 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domain',
            name='subdomains',
        ),
        migrations.AddField(
            model_name='domain',
            name='subdomains',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subdomain', to='core.domain'),
        ),
        migrations.RemoveField(
            model_name='domain',
            name='techs',
        ),
        migrations.AddField(
            model_name='domain',
            name='techs',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='techs', to='core.tech'),
        ),
        migrations.RemoveField(
            model_name='subdomain',
            name='techs',
        ),
        migrations.AddField(
            model_name='subdomain',
            name='techs',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.tech'),
        ),
        migrations.RemoveField(
            model_name='tech',
            name='cves',
        ),
        migrations.AddField(
            model_name='tech',
            name='cves',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.cve'),
        ),
        migrations.RemoveField(
            model_name='user',
            name='domains',
        ),
        migrations.AddField(
            model_name='user',
            name='domains',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.domain'),
        ),
    ]
