# Generated by Django 4.0.4 on 2022-06-08 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_cve_cve_id_remove_cve_isnew'),
    ]

    operations = [
        migrations.AddField(
            model_name='cve',
            name='cve_id',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='cve',
            name='isNew',
            field=models.BooleanField(default=True),
        ),
    ]
