# Generated by Django 4.0.4 on 2022-05-09 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_domain_subdomains_domain_subdomains_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='subdomains',
            field=models.ManyToManyField(blank=True, to='core.subdomain'),
        ),
    ]
