# Generated by Django 4.0.4 on 2022-05-10 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_domain_subdomains'),
    ]

    operations = [
        migrations.RenameField(
            model_name='domain',
            old_name='name',
            new_name='full_name',
        ),
    ]
