# Generated by Django 4.0.4 on 2022-06-08 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_cve_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='cve',
            name='isSeen',
            field=models.BooleanField(default=False),
        ),
    ]
