# Generated by Django 4.0.4 on 2022-06-09 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_cve_isseen'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='cron_interval',
            field=models.PositiveSmallIntegerField(default=2),
        ),
    ]
