# Generated by Django 4.0.4 on 2022-05-10 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_name_domain_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tech',
            name='color',
            field=models.CharField(default='c4c4c4', max_length=6),
        ),
    ]
