# Generated by Django 4.0.4 on 2022-06-10 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_subdomain_created_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subdomain',
            options={'ordering': ['-created_date']},
        ),
        migrations.AddField(
            model_name='tech',
            name='updating_cve',
            field=models.BooleanField(default=False),
        ),
    ]
