# Generated by Django 4.0.4 on 2022-06-10 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_tech_updating_cve'),
    ]

    operations = [
        migrations.AddField(
            model_name='tech',
            name='updating_cve',
            field=models.BooleanField(default=False),
        ),
    ]
