# Generated by Django 4.0.4 on 2022-07-05 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_tech_updating_cve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tech',
            name='updating_cve',
            field=models.BooleanField(default=True),
        ),
    ]
