# Generated by Django 4.0.4 on 2022-07-05 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_tech_updating_cve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cve',
            name='cve_id',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
    ]
