# Generated by Django 4.0.4 on 2022-07-05 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_cve_cve_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cve',
            name='cve_id',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='cve',
            name='tech_id',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='cve',
            unique_together={('cve_id', 'tech_id')},
        ),
    ]
