# Generated by Django 4.0.4 on 2022-07-05 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_tech_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tech',
            name='author',
        ),
    ]
