# Generated by Django 4.0.4 on 2022-07-07 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0016_tech_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='domain',
            name='verify_code',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
