# Generated by Django 4.0.4 on 2022-07-07 10:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0017_alter_domain_author_alter_domain_verify_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='domain',
            name='verify_code',
            field=models.PositiveIntegerField(),
        ),
    ]
